"""empty message

Revision ID: 539521267fbb
Revises: 
Create Date: 2017-05-11 22:15:37.092223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539521267fbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('act_score', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('description', sa.UnicodeText(), nullable=True))
    op.add_column('user', sa.Column('image', sa.UnicodeText(), nullable=True))
    op.add_column('user', sa.Column('major', sa.UnicodeText(), nullable=True))
    op.add_column('user', sa.Column('sat_math', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('sat_reading', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('sat_writing', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('school', sa.UnicodeText(), nullable=True))
    op.add_column('user', sa.Column('skype_username', sa.UnicodeText(), nullable=True))
    op.add_column('user', sa.Column('year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_act_score'), 'user', ['act_score'], unique=False)
    op.create_index(op.f('ix_user_sat_math'), 'user', ['sat_math'], unique=False)
    op.create_index(op.f('ix_user_sat_reading'), 'user', ['sat_reading'], unique=False)
    op.create_index(op.f('ix_user_sat_writing'), 'user', ['sat_writing'], unique=False)
    op.create_index(op.f('ix_user_year'), 'user', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_year'), table_name='user')
    op.drop_index(op.f('ix_user_sat_writing'), table_name='user')
    op.drop_index(op.f('ix_user_sat_reading'), table_name='user')
    op.drop_index(op.f('ix_user_sat_math'), table_name='user')
    op.drop_index(op.f('ix_user_act_score'), table_name='user')
    op.drop_column('user', 'year')
    op.drop_column('user', 'skype_username')
    op.drop_column('user', 'school')
    op.drop_column('user', 'sat_writing')
    op.drop_column('user', 'sat_reading')
    op.drop_column('user', 'sat_math')
    op.drop_column('user', 'major')
    op.drop_column('user', 'image')
    op.drop_column('user', 'description')
    op.drop_column('user', 'act_score')
    # ### end Alembic commands ###
